title: Toko Bunga Lampung # your site title
author: Asry Florist
email: bungaku.cs@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Toko Bunga di Lampung Asry Florist kirim bunga ucapan dan buket mawar segar murah online 24 jam.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tokobungadilampung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AsryFlorist # replace with your_twitter_username or comment to remove link from footer
github_username:  tokobungadilampung # replace with your_github_username or comment to remove link from footer
instagram_username: bungabuketmawar # replace with your_instagram_username or comment to remove link from footer
social:
  name: Asry Florist
  links:
    - https://twitter.com/AsryFlorist
    - https://www.facebook.com/asryflorist
    - https://www.linkedin.com/in/asryflorist
    - https://plus.google.com/+asryflorist
    - https://github.com/tokobungadilampung
    - https://keybase.io/asryflorist

disqus:
  shortname: tokobungalampung # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
